# Generated by Django 3.1 on 2020-08-10 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='elearning.lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('BOOLEAN', 'BOOLEAN'), ('MULTIPLE_CHOOSE_A_CORRECT_ONE', 'MULTIPLE_CHOOSE_A_CORRECT_ONE'), ('CHOOSE_ALL_THE_RIGHT', 'CHOOSE_ALL_THE_RIGHT')], default='MULTIPLE_CHOOSE_A_CORRECT_ONE', max_length=200),
        ),
    ]
