# Generated by Django 3.1 on 2020-08-10 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_auto_20200810_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollment',
            old_name='enrollment',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lessonenrollment',
            old_name='enrollment',
            new_name='lesson',
        ),
    ]
