# Generated by Django 3.1 on 2020-08-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20200810_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ancestor',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ancestor',
        ),
        migrations.AddField(
            model_name='course',
            name='dependent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predecessor_course', to='elearning.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='dependent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predecessor_lesson', to='elearning.lesson'),
        ),
    ]
