# Generated by Django 3.1 on 2020-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_auto_20200810_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonenrollment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
