# Generated by Django 3.1 on 2020-08-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_auto_20200810_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
