"""
Api specific settings
"""

QUESTION_TYPES = (
    ('BOOLEAN', 'BOOLEAN'),
    ('MULTIPLE_CHOOSE_A_CORRECT_ONE', 'MULTIPLE_CHOOSE_A_CORRECT_ONE'),
    ('CHOOSE_ALL_THE_RIGHT', 'CHOOSE_ALL_THE_RIGHT'),
)
